var WorkData = {
  dance: {
    1: {
      cover: require("../image/work/dance/台中盃/DSC00153.jpg"),
      title: "台中杯",
      text: "text",
      images: {
        1: require("../image/work/dance/台中盃/DSC00153.jpg"),
        2: require("../image/work/dance/台中盃/DSC00395.jpg"),
        3: require("../image/work/dance/台中盃/DSC01493.jpg"),
        4: require("../image/work/dance/台中盃/DSC01889.jpg"),
        5: require("../image/work/dance/台中盃/DSC01982.jpg"),
        6: require("../image/work/dance/台中盃/DSC02013.jpg"),
        7: require("../image/work/dance/台中盃/DSC03284.jpg"),
        8: require("../image/work/dance/台中盃/DSC04044.jpg"),
        9: require("../image/work/dance/台中盃/DSC04049.jpg"),
        10: require("../image/work/dance/台中盃/DSC04089.jpg"),
        11: require("../image/work/dance/台中盃/DSC04498.jpg"),
        12: require("../image/work/dance/台中盃/DSC04548.jpg"),
        13: require("../image/work/dance/台中盃/DSC04551.jpg"),
        14: require("../image/work/dance/台中盃/DSC04636.jpg"),
        15: require("../image/work/dance/台中盃/DSC05177.jpg"),
        16: require("../image/work/dance/台中盃/DSC05320.jpg"),
        17: require("../image/work/dance/台中盃/DSC05925.jpg"),
        18: require("../image/work/dance/台中盃/DSC06056.jpg"),
        19: require("../image/work/dance/台中盃/DSC06057.jpg"),
        20: require("../image/work/dance/台中盃/DSC06086.jpg"),
        21: require("../image/work/dance/台中盃/DSC06284.jpg"),
        22: require("../image/work/dance/台中盃/DSC06324.jpg"),
        23: require("../image/work/dance/台中盃/DSC06367.jpg"),
        24: require("../image/work/dance/台中盃/DSC06546.jpg"),
        25: require("../image/work/dance/台中盃/DSC07047.jpg"),
        26: require("../image/work/dance/台中盃/DSC07386.jpg"),
        27: require("../image/work/dance/台中盃/DSC07392.jpg"),
        28: require("../image/work/dance/台中盃/DSC08072.jpg"),
        29: require("../image/work/dance/台中盃/DSC08695.jpg"),
        30: require("../image/work/dance/台中盃/DSC08955.jpg"),
        31: require("../image/work/dance/台中盃/DSC09069.jpg"),
        32: require("../image/work/dance/台中盃/DSC09243.jpg"),
        33: require("../image/work/dance/台中盃/DSC09470.jpg"),
        34: require("../image/work/dance/台中盃/DSC09799.jpg"),
      },
    },
    2: {
      cover: require("../image/work/dance/養手盃/弘光battle-109.jpg"),
      title: "養手盃",
      text: "text",
      images: {
        1: require("../image/work/dance/養手盃/弘光battle-109.jpg"),
        2: require("../image/work/dance/養手盃/弘光battle-136.jpg"),
        3: require("../image/work/dance/養手盃/弘光battle-171.jpg"),
        4: require("../image/work/dance/養手盃/弘光battle-230.jpg"),
        5: require("../image/work/dance/養手盃/弘光battle-280.jpg"),
        6: require("../image/work/dance/養手盃/弘光battle-287.jpg"),
        7: require("../image/work/dance/養手盃/弘光battle-305.jpg"),
        8: require("../image/work/dance/養手盃/弘光battle-32.jpg"),
        9: require("../image/work/dance/養手盃/弘光battle-346.jpg"),
        10: require("../image/work/dance/養手盃/弘光battle-412.jpg"),
        11: require("../image/work/dance/養手盃/弘光battle-435.jpg"),
        12: require("../image/work/dance/養手盃/弘光battle-445.jpg"),
        13: require("../image/work/dance/養手盃/弘光battle-454.jpg"),
        14: require("../image/work/dance/養手盃/弘光battle-470.jpg"),
        15: require("../image/work/dance/養手盃/弘光battle-520.jpg"),
        16: require("../image/work/dance/養手盃/弘光battle-523.jpg"),
        17: require("../image/work/dance/養手盃/弘光battle-527.jpg"),
        18: require("../image/work/dance/養手盃/弘光battle-579.jpg"),
        19: require("../image/work/dance/養手盃/弘光battle-645.jpg"),
        20: require("../image/work/dance/養手盃/弘光battle-66.jpg"),
      },
    },
    3: {
      cover: require("../image/work/dance/parij/parij-101.jpg"),
      title: "parij",
      text: "text",
      images: {
        1: require("../image/work/dance/parij/parij-101.jpg"),
        2: require("../image/work/dance/parij/parij-139.jpg"),
        3: require("../image/work/dance/parij/parij-16.jpg"),
        4: require("../image/work/dance/parij/parij-166.jpg"),
        5: require("../image/work/dance/parij/parij-171.jpg"),
        6: require("../image/work/dance/parij/parij-204.jpg"),
        7: require("../image/work/dance/parij/parij-205.jpg"),
        8: require("../image/work/dance/parij/parij-216.jpg"),
        9: require("../image/work/dance/parij/parij-217.jpg"),
        10: require("../image/work/dance/parij/parij-262.jpg"),
        11: require("../image/work/dance/parij/parij-319.jpg"),
        12: require("../image/work/dance/parij/parij-322.jpg"),
        13: require("../image/work/dance/parij/parij-326.jpg"),
        14: require("../image/work/dance/parij/parij-328.jpg"),
        15: require("../image/work/dance/parij/parij-334.jpg"),
        16: require("../image/work/dance/parij/parij-335.jpg"),
        17: require("../image/work/dance/parij/parij-361.jpg"),
        18: require("../image/work/dance/parij/parij-6.jpg"),
        19: require("../image/work/dance/parij/parij-71.jpg"),
        20: require("../image/work/dance/parij/parij-73.jpg"),
        21: require("../image/work/dance/parij/parij-87.jpg"),
        22: require("../image/work/dance/parij/parij-90.jpg"),
        23: require("../image/work/dance/parij/parij-91.jpg"),
        24: require("../image/work/dance/parij/parij-95.jpg"),
      },
    },
    4: {
      cover: require("../image/work/dance/hero-4-Who/h4w 前夜祭-106.jpg"),
      title: "hero 4 Who",
      text: "70",
      images: {
        1: require("../image/work/dance/hero-4-Who/h4w 前夜祭-106.jpg"),
        2: require("../image/work/dance/hero-4-Who/h4w 前夜祭-112.jpg"),
        3: require("../image/work/dance/hero-4-Who/h4w 前夜祭-117.jpg"),
        4: require("../image/work/dance/hero-4-Who/h4w 前夜祭-128.jpg"),
        5: require("../image/work/dance/hero-4-Who/h4w 前夜祭-140.jpg"),
        6: require("../image/work/dance/hero-4-Who/h4w 前夜祭-143.jpg"),
        7: require("../image/work/dance/hero-4-Who/h4w 前夜祭-149.jpg"),
        8: require("../image/work/dance/hero-4-Who/h4w 前夜祭-154.jpg"),
        9: require("../image/work/dance/hero-4-Who/h4w 前夜祭-168.jpg"),
        10: require("../image/work/dance/hero-4-Who/h4w 前夜祭-179.jpg"),
        11: require("../image/work/dance/hero-4-Who/h4w 前夜祭-190.jpg"),
        12: require("../image/work/dance/hero-4-Who/h4w 前夜祭-193.jpg"),
        13: require("../image/work/dance/hero-4-Who/h4w 前夜祭-194.jpg"),
        14: require("../image/work/dance/hero-4-Who/h4w 前夜祭-196.jpg"),
        15: require("../image/work/dance/hero-4-Who/h4w 前夜祭-199.jpg"),
        16: require("../image/work/dance/hero-4-Who/h4w 前夜祭-205.jpg"),
        17: require("../image/work/dance/hero-4-Who/h4w 前夜祭-206.jpg"),
        18: require("../image/work/dance/hero-4-Who/h4w 前夜祭-208.jpg"),
        19: require("../image/work/dance/hero-4-Who/h4w 前夜祭-21.jpg"),
        20: require("../image/work/dance/hero-4-Who/h4w 前夜祭-217.jpg"),
        21: require("../image/work/dance/hero-4-Who/h4w 前夜祭-225.jpg"),
        22: require("../image/work/dance/hero-4-Who/h4w 前夜祭-236.jpg"),
        23: require("../image/work/dance/hero-4-Who/h4w 前夜祭-25.jpg"),
        24: require("../image/work/dance/hero-4-Who/h4w 前夜祭-251.jpg"),
        25: require("../image/work/dance/hero-4-Who/h4w 前夜祭-26.jpg"),
        26: require("../image/work/dance/hero-4-Who/h4w 前夜祭-37.jpg"),
        27: require("../image/work/dance/hero-4-Who/h4w 前夜祭-379.jpg"),
        28: require("../image/work/dance/hero-4-Who/h4w 前夜祭-383.jpg"),
        29: require("../image/work/dance/hero-4-Who/h4w 前夜祭-51.jpg"),
        30: require("../image/work/dance/hero-4-Who/h4w 前夜祭-55.jpg"),
        31: require("../image/work/dance/hero-4-Who/h4w 前夜祭-60.jpg"),
        32: require("../image/work/dance/hero-4-Who/h4w 前夜祭-64.jpg"),
        33: require("../image/work/dance/hero-4-Who/h4w 前夜祭-713.jpg"),
        34: require("../image/work/dance/hero-4-Who/h4w 前夜祭-95.jpg"),
        35: require("../image/work/dance/hero-4-Who/h4w 台中-14.jpg"),
        36: require("../image/work/dance/hero-4-Who/h4w 台中-319.jpg"),
        37: require("../image/work/dance/hero-4-Who/h4w 台中-325.jpg"),
        38: require("../image/work/dance/hero-4-Who/h4w 台中-329.jpg"),
        39: require("../image/work/dance/hero-4-Who/h4w 台中-339.jpg"),
        40: require("../image/work/dance/hero-4-Who/h4w 決賽-201.jpg"),
        41: require("../image/work/dance/hero-4-Who/h4w 決賽-208.jpg"),
        42: require("../image/work/dance/hero-4-Who/h4w 決賽-221.jpg"),
        43: require("../image/work/dance/hero-4-Who/h4w 決賽-223.jpg"),
        44: require("../image/work/dance/hero-4-Who/h4w 決賽-236.jpg"),
        45: require("../image/work/dance/hero-4-Who/h4w 決賽-245.jpg"),
        46: require("../image/work/dance/hero-4-Who/h4w 決賽-251.jpg"),
        47: require("../image/work/dance/hero-4-Who/h4w 決賽-253.jpg"),
        48: require("../image/work/dance/hero-4-Who/h4w 決賽-266.jpg"),
        49: require("../image/work/dance/hero-4-Who/h4w 決賽-270.jpg"),
        50: require("../image/work/dance/hero-4-Who/h4w 決賽-480.jpg"),
        51: require("../image/work/dance/hero-4-Who/h4w 決賽-496.jpg"),
        52: require("../image/work/dance/hero-4-Who/h4w 決賽-511.jpg"),
        53: require("../image/work/dance/hero-4-Who/h4w 決賽-519.jpg"),
        54: require("../image/work/dance/hero-4-Who/h4w 決賽-564.jpg"),
        55: require("../image/work/dance/hero-4-Who/h4w 決賽-700.jpg"),
        56: require("../image/work/dance/hero-4-Who/h4w 決賽-707.jpg"),
        57: require("../image/work/dance/hero-4-Who/h4w 決賽-723.jpg"),
        58: require("../image/work/dance/hero-4-Who/h4w 決賽-725.jpg"),
        59: require("../image/work/dance/hero-4-Who/h4w 決賽-730.jpg"),
        60: require("../image/work/dance/hero-4-Who/h4w 決賽-732.jpg"),
        61: require("../image/work/dance/hero-4-Who/h4w 決賽-751.jpg"),
        62: require("../image/work/dance/hero-4-Who/h4w 決賽-752.jpg"),
        63: require("../image/work/dance/hero-4-Who/h4w 決賽-774.jpg"),
        64: require("../image/work/dance/hero-4-Who/h4w 決賽-808.jpg"),
        65: require("../image/work/dance/hero-4-Who/h4w 決賽-809.jpg"),
        66: require("../image/work/dance/hero-4-Who/h4w 高雄-20.jpg"),
        67: require("../image/work/dance/hero-4-Who/h4w 高雄-267.jpg"),
        68: require("../image/work/dance/hero-4-Who/h4w 高雄-275.jpg"),
        69: require("../image/work/dance/hero-4-Who/h4w 高雄-371.jpg"),
        70: require("../image/work/dance/hero-4-Who/h4w 高雄-381.jpg"),
      },
    },
  },
  life: {
    1: {
      cover: require("../image/work/life/17宜蘭行/17宜蘭-149.jpg"),
      title: "17宜蘭行",
      text: "27",
      images: {
        1: require("../image/work/life/17宜蘭行/17宜蘭-149.jpg"),
        2: require("../image/work/life/17宜蘭行/17宜蘭-165.jpg"),
        3: require("../image/work/life/17宜蘭行/17宜蘭-202.jpg"),
        4: require("../image/work/life/17宜蘭行/17宜蘭-232.jpg"),
        5: require("../image/work/life/17宜蘭行/17宜蘭-243.jpg"),
        6: require("../image/work/life/17宜蘭行/17宜蘭-244.jpg"),
        7: require("../image/work/life/17宜蘭行/17宜蘭-247.jpg"),
        8: require("../image/work/life/17宜蘭行/17宜蘭-251.jpg"),
        9: require("../image/work/life/17宜蘭行/17宜蘭-252.jpg"),
        10: require("../image/work/life/17宜蘭行/17宜蘭-274.jpg"),
        11: require("../image/work/life/17宜蘭行/17宜蘭-307.jpg"),
        12: require("../image/work/life/17宜蘭行/17宜蘭-353.jpg"),
        13: require("../image/work/life/17宜蘭行/17宜蘭-367.jpg"),
        14: require("../image/work/life/17宜蘭行/17宜蘭-375.jpg"),
        15: require("../image/work/life/17宜蘭行/17宜蘭-389.jpg"),
        16: require("../image/work/life/17宜蘭行/17宜蘭-399.jpg"),
        17: require("../image/work/life/17宜蘭行/17宜蘭-402.jpg"),
        18: require("../image/work/life/17宜蘭行/17宜蘭-405.jpg"),
        19: require("../image/work/life/17宜蘭行/17宜蘭-41.jpg"),
        20: require("../image/work/life/17宜蘭行/17宜蘭-418.jpg"),
        21: require("../image/work/life/17宜蘭行/17宜蘭-449.jpg"),
        22: require("../image/work/life/17宜蘭行/17宜蘭-45.jpg"),
        23: require("../image/work/life/17宜蘭行/17宜蘭-478.jpg"),
        24: require("../image/work/life/17宜蘭行/17宜蘭-480.jpg"),
        25: require("../image/work/life/17宜蘭行/17宜蘭-49.jpg"),
        26: require("../image/work/life/17宜蘭行/17宜蘭-82.jpg"),
        27: require("../image/work/life/17宜蘭行/17宜蘭-83.jpg"),
      },
    },
    2: {
      cover: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-1.jpg"),
      title: "22.05.25 霧峰隨手拍",
      text: "15",
      images: {
        1: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-1.jpg"),
        2: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-10.jpg"),
        3: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-11.jpg"),
        4: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-12.jpg"),
        5: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-13.jpg"),
        6: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-14.jpg"),
        7: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-15.jpg"),
        8: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-2.jpg"),
        9: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-3.jpg"),
        10: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-4.jpg"),
        11: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-5.jpg"),
        12: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-6.jpg"),
        13: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-7.jpg"),
        14: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-8.jpg"),
        15: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-9.jpg"),
      },
    },
    3: {
      cover: require("../image/work/life/宮原眼科/h4w-115.jpg"),
      title: "宮原眼科",
      text: "3",
      images: {
        1: require("../image/work/life/宮原眼科/h4w-115.jpg"),
        2: require("../image/work/life/宮原眼科/眼科-1.jpg"),
        3: require("../image/work/life/宮原眼科/眼科-2 P出.png"),
      },
    },
  },
  house: {
    1: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    2: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    3: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    4: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    5: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
  },
  art_activity: {
    1: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    2: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    3: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    4: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    5: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
  },
  people: {
    1: {
      cover: require("../image/work/people/六福村-DBD/六福村-12.jpg"),
      title: "六福村-DBD",
      text: "text",
      images: {
        1: require("../image/work/people/六福村-DBD/六福村-12.jpg"),
        2: require("../image/work/people/六福村-DBD/六福村-13.jpg"),
        3: require("../image/work/people/六福村-DBD/六福村-14.jpg"),
        4: require("../image/work/people/六福村-DBD/六福村-22.jpg"),
        5: require("../image/work/people/六福村-DBD/六福村-23.jpg"),
        6: require("../image/work/people/六福村-DBD/六福村-24.jpg"),
        7: require("../image/work/people/六福村-DBD/六福村-27.jpg"),
      },
    },
    2: {
      cover: require("../image/work/people/史萊姆T/ 史萊姆-小鈴_補拍-11.jpg"),
      title: "史萊姆Ｔ",
      text: "text",
      images: {
        1: require("../image/work/people/史萊姆T/ 史萊姆-小鈴_補拍-11.jpg"),
        2: require("../image/work/people/史萊姆T/ 史萊姆-小鈴_補拍-14.jpg"),
        3: require("../image/work/people/史萊姆T/ 史萊姆-小鈴_補拍-20.jpg"),
        4: require("../image/work/people/史萊姆T/ 史萊姆-小鈴_補拍-32.jpg"),
        5: require("../image/work/people/史萊姆T/ 史萊姆-小鈴_補拍-37.jpg"),
        6: require("../image/work/people/史萊姆T/ 史萊姆-小鈴_補拍-4.jpg"),
        7: require("../image/work/people/史萊姆T/史萊姆-小鈴-24.jpg"),
        8: require("../image/work/people/史萊姆T/史萊姆-小鈴-30.jpg"),
        9: require("../image/work/people/史萊姆T/史萊姆-小鈴-34.jpg"),
        10: require("../image/work/people/史萊姆T/史萊姆-小鈴-37.jpg"),
        11: require("../image/work/people/史萊姆T/史萊姆-小鈴-4.jpg"),
        12: require("../image/work/people/史萊姆T/史萊姆-小鈴-47.jpg"),
      },
    },
    3: {
      cover: require("../image/work/people/白衣女子/11.12 廢墟-1.jpg"),
      title: "白衣女子",
      text: "text",
      images: {
        1: require("../image/work/people/白衣女子/11.12 廢墟-1.jpg"),
        2: require("../image/work/people/白衣女子/11.12 廢墟-11.jpg"),
        3: require("../image/work/people/白衣女子/11.12 廢墟-15.jpg"),
        4: require("../image/work/people/白衣女子/11.12 廢墟-17.jpg"),
        5: require("../image/work/people/白衣女子/11.12 廢墟-20.jpg"),
        6: require("../image/work/people/白衣女子/11.12 廢墟-26.jpg"),
        7: require("../image/work/people/白衣女子/11.12 廢墟-27.jpg"),
        8: require("../image/work/people/白衣女子/11.12 廢墟-28.jpg"),
        9: require("../image/work/people/白衣女子/11.12 廢墟-33.jpg"),
        10: require("../image/work/people/白衣女子/11.12 廢墟-5.jpg"),
      },
    },
    4: {
      cover: require("../image/work/people/廢墟/11.12 廢墟-11.jpg"),
      title: "廢墟",
      text: "text",
      images: {
        1: require("../image/work/people/廢墟/11.12 廢墟-11.jpg"),
        2: require("../image/work/people/廢墟/11.12 廢墟-13.jpg"),
        3: require("../image/work/people/廢墟/11.12 廢墟-18.jpg"),
        4: require("../image/work/people/廢墟/11.12 廢墟-19.jpg"),
        5: require("../image/work/people/廢墟/11.12 廢墟-23.jpg"),
        6: require("../image/work/people/廢墟/11.12 廢墟-30.jpg"),
        7: require("../image/work/people/廢墟/11.12 廢墟-31.jpg"),
        8: require("../image/work/people/廢墟/11.12 廢墟-34.jpg"),
        9: require("../image/work/people/廢墟/11.12 廢墟-41.jpg"),
        10: require("../image/work/people/廢墟/11.12 廢墟-43.jpg"),
        11: require("../image/work/people/廢墟/11.12 廢墟-45.jpg"),
        12: require("../image/work/people/廢墟/11.12 廢墟-5.jpg"),
        13: require("../image/work/people/廢墟/11.12 廢墟-7.jpg"),
        14: require("../image/work/people/廢墟/11.12 廢墟-8.jpg"),
      },
    },
  },
  product: {
    1: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    2: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    3: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    4: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    5: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
  },
  toy: {
    1: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    2: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    3: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    4: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    5: {
      cover: require("../image/work/dance/main.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
  },
};
export default WorkData;
