var WorkData = {
  dance: {
    1: {
      cover: require("../image/work/dance/台中盃/DSC01493.jpg"),
      title: "台中杯",
      text: "text",
      images: {
        1: require("../image/work/dance/台中盃/DSC00395.jpg"),
        2: require("../image/work/dance/台中盃/DSC00153.jpg"),
        3: require("../image/work/dance/台中盃/DSC01493.jpg"),
        4: require("../image/work/dance/台中盃/DSC01889.jpg"),
        5: require("../image/work/dance/台中盃/DSC01982.jpg"),
        6: require("../image/work/dance/台中盃/DSC02013.jpg"),
        7: require("../image/work/dance/台中盃/DSC03284.jpg"),
        8: require("../image/work/dance/台中盃/DSC04044.jpg"),
        9: require("../image/work/dance/台中盃/DSC04049.jpg"),
        10: require("../image/work/dance/台中盃/DSC04089.jpg"),
        11: require("../image/work/dance/台中盃/DSC04498.jpg"),
        12: require("../image/work/dance/台中盃/DSC04548.jpg"),
        13: require("../image/work/dance/台中盃/DSC04551.jpg"),
        14: require("../image/work/dance/台中盃/DSC04636.jpg"),
        15: require("../image/work/dance/台中盃/DSC05177.jpg"),
        16: require("../image/work/dance/台中盃/DSC05320.jpg"),
        17: require("../image/work/dance/台中盃/DSC05925.jpg"),
        18: require("../image/work/dance/台中盃/DSC06056.jpg"),
        19: require("../image/work/dance/台中盃/DSC06057.jpg"),
        20: require("../image/work/dance/台中盃/DSC06086.jpg"),
        21: require("../image/work/dance/台中盃/DSC06284.jpg"),
        22: require("../image/work/dance/台中盃/DSC06324.jpg"),
        23: require("../image/work/dance/台中盃/DSC06367.jpg"),
        24: require("../image/work/dance/台中盃/DSC06546.jpg"),
        25: require("../image/work/dance/台中盃/DSC07047.jpg"),
        26: require("../image/work/dance/台中盃/DSC07386.jpg"),
        27: require("../image/work/dance/台中盃/DSC07392.jpg"),
        28: require("../image/work/dance/台中盃/DSC08072.jpg"),
        29: require("../image/work/dance/台中盃/DSC08695.jpg"),
        30: require("../image/work/dance/台中盃/DSC08955.jpg"),
        31: require("../image/work/dance/台中盃/DSC09069.jpg"),
        32: require("../image/work/dance/台中盃/DSC09243.jpg"),
        33: require("../image/work/dance/台中盃/DSC09470.jpg"),
        34: require("../image/work/dance/台中盃/DSC09799.jpg"),
      },
    },
    2: {
      cover: require("../image/work/dance/養手盃/弘光battle-109.jpg"),
      title: "養手盃",
      text: "text",
      images: {
        1: require("../image/work/dance/養手盃/弘光battle-109.jpg"),
        2: require("../image/work/dance/養手盃/弘光battle-136.jpg"),
        3: require("../image/work/dance/養手盃/弘光battle-171.jpg"),
        4: require("../image/work/dance/養手盃/弘光battle-230.jpg"),
        5: require("../image/work/dance/養手盃/弘光battle-280.jpg"),
        6: require("../image/work/dance/養手盃/弘光battle-287.jpg"),
        7: require("../image/work/dance/養手盃/弘光battle-305.jpg"),
        8: require("../image/work/dance/養手盃/弘光battle-32.jpg"),
        9: require("../image/work/dance/養手盃/弘光battle-346.jpg"),
        10: require("../image/work/dance/養手盃/弘光battle-412.jpg"),
        11: require("../image/work/dance/養手盃/弘光battle-435.jpg"),
        12: require("../image/work/dance/養手盃/弘光battle-445.jpg"),
        13: require("../image/work/dance/養手盃/弘光battle-454.jpg"),
        14: require("../image/work/dance/養手盃/弘光battle-470.jpg"),
        15: require("../image/work/dance/養手盃/弘光battle-520.jpg"),
        16: require("../image/work/dance/養手盃/弘光battle-523.jpg"),
        17: require("../image/work/dance/養手盃/弘光battle-527.jpg"),
        18: require("../image/work/dance/養手盃/弘光battle-579.jpg"),
        19: require("../image/work/dance/養手盃/弘光battle-645.jpg"),
        20: require("../image/work/dance/養手盃/弘光battle-66.jpg"),
      },
    },
    3: {
      cover: require("../image/work/dance/parij/parij-101.jpg"),
      title: "parij",
      text: "text",
      images: {
        1: require("../image/work/dance/parij/parij-101.jpg"),
        2: require("../image/work/dance/parij/parij-139.jpg"),
        3: require("../image/work/dance/parij/parij-16.jpg"),
        4: require("../image/work/dance/parij/parij-166.jpg"),
        5: require("../image/work/dance/parij/parij-171.jpg"),
        6: require("../image/work/dance/parij/parij-204.jpg"),
        7: require("../image/work/dance/parij/parij-205.jpg"),
        8: require("../image/work/dance/parij/parij-216.jpg"),
        9: require("../image/work/dance/parij/parij-217.jpg"),
        10: require("../image/work/dance/parij/parij-262.jpg"),
        11: require("../image/work/dance/parij/parij-319.jpg"),
        12: require("../image/work/dance/parij/parij-322.jpg"),
        13: require("../image/work/dance/parij/parij-326.jpg"),
        14: require("../image/work/dance/parij/parij-328.jpg"),
        15: require("../image/work/dance/parij/parij-334.jpg"),
        16: require("../image/work/dance/parij/parij-335.jpg"),
        17: require("../image/work/dance/parij/parij-361.jpg"),
        18: require("../image/work/dance/parij/parij-6.jpg"),
        19: require("../image/work/dance/parij/parij-71.jpg"),
        20: require("../image/work/dance/parij/parij-73.jpg"),
        21: require("../image/work/dance/parij/parij-87.jpg"),
        22: require("../image/work/dance/parij/parij-90.jpg"),
        23: require("../image/work/dance/parij/parij-91.jpg"),
        24: require("../image/work/dance/parij/parij-95.jpg"),
      },
    },
    4: {
      cover: require("../image/work/dance/hero-4-Who/h4w 前夜祭-106.jpg"),
      title: "hero 4 Who",
      text: "70",
      images: {
        1: require("../image/work/dance/hero-4-Who/h4w 前夜祭-106.jpg"),
        2: require("../image/work/dance/hero-4-Who/h4w 前夜祭-112.jpg"),
        3: require("../image/work/dance/hero-4-Who/h4w 前夜祭-117.jpg"),
        4: require("../image/work/dance/hero-4-Who/h4w 前夜祭-128.jpg"),
        5: require("../image/work/dance/hero-4-Who/h4w 前夜祭-140.jpg"),
        6: require("../image/work/dance/hero-4-Who/h4w 前夜祭-143.jpg"),
        7: require("../image/work/dance/hero-4-Who/h4w 前夜祭-149.jpg"),
        8: require("../image/work/dance/hero-4-Who/h4w 前夜祭-154.jpg"),
        9: require("../image/work/dance/hero-4-Who/h4w 前夜祭-168.jpg"),
        10: require("../image/work/dance/hero-4-Who/h4w 前夜祭-179.jpg"),
        11: require("../image/work/dance/hero-4-Who/h4w 前夜祭-190.jpg"),
        12: require("../image/work/dance/hero-4-Who/h4w 前夜祭-193.jpg"),
        13: require("../image/work/dance/hero-4-Who/h4w 前夜祭-194.jpg"),
        14: require("../image/work/dance/hero-4-Who/h4w 前夜祭-196.jpg"),
        15: require("../image/work/dance/hero-4-Who/h4w 前夜祭-199.jpg"),
        16: require("../image/work/dance/hero-4-Who/h4w 前夜祭-205.jpg"),
        17: require("../image/work/dance/hero-4-Who/h4w 前夜祭-206.jpg"),
        18: require("../image/work/dance/hero-4-Who/h4w 前夜祭-208.jpg"),
        19: require("../image/work/dance/hero-4-Who/h4w 前夜祭-21.jpg"),
        20: require("../image/work/dance/hero-4-Who/h4w 前夜祭-217.jpg"),
        21: require("../image/work/dance/hero-4-Who/h4w 前夜祭-225.jpg"),
        22: require("../image/work/dance/hero-4-Who/h4w 前夜祭-236.jpg"),
        23: require("../image/work/dance/hero-4-Who/h4w 前夜祭-25.jpg"),
        24: require("../image/work/dance/hero-4-Who/h4w 前夜祭-251.jpg"),
        25: require("../image/work/dance/hero-4-Who/h4w 前夜祭-26.jpg"),
        26: require("../image/work/dance/hero-4-Who/h4w 前夜祭-37.jpg"),
        27: require("../image/work/dance/hero-4-Who/h4w 前夜祭-379.jpg"),
        28: require("../image/work/dance/hero-4-Who/h4w 前夜祭-383.jpg"),
        29: require("../image/work/dance/hero-4-Who/h4w 前夜祭-51.jpg"),
        30: require("../image/work/dance/hero-4-Who/h4w 前夜祭-55.jpg"),
        31: require("../image/work/dance/hero-4-Who/h4w 前夜祭-60.jpg"),
        32: require("../image/work/dance/hero-4-Who/h4w 前夜祭-64.jpg"),
        33: require("../image/work/dance/hero-4-Who/h4w 前夜祭-713.jpg"),
        34: require("../image/work/dance/hero-4-Who/h4w 前夜祭-95.jpg"),
        35: require("../image/work/dance/hero-4-Who/h4w 台中-14.jpg"),
        36: require("../image/work/dance/hero-4-Who/h4w 台中-319.jpg"),
        37: require("../image/work/dance/hero-4-Who/h4w 台中-325.jpg"),
        38: require("../image/work/dance/hero-4-Who/h4w 台中-329.jpg"),
        39: require("../image/work/dance/hero-4-Who/h4w 台中-339.jpg"),
        40: require("../image/work/dance/hero-4-Who/h4w 決賽-201.jpg"),
        41: require("../image/work/dance/hero-4-Who/h4w 決賽-208.jpg"),
        42: require("../image/work/dance/hero-4-Who/h4w 決賽-221.jpg"),
        43: require("../image/work/dance/hero-4-Who/h4w 決賽-223.jpg"),
        44: require("../image/work/dance/hero-4-Who/h4w 決賽-236.jpg"),
        45: require("../image/work/dance/hero-4-Who/h4w 決賽-245.jpg"),
        46: require("../image/work/dance/hero-4-Who/h4w 決賽-251.jpg"),
        47: require("../image/work/dance/hero-4-Who/h4w 決賽-253.jpg"),
        48: require("../image/work/dance/hero-4-Who/h4w 決賽-266.jpg"),
        49: require("../image/work/dance/hero-4-Who/h4w 決賽-270.jpg"),
        50: require("../image/work/dance/hero-4-Who/h4w 決賽-480.jpg"),
        51: require("../image/work/dance/hero-4-Who/h4w 決賽-496.jpg"),
        52: require("../image/work/dance/hero-4-Who/h4w 決賽-511.jpg"),
        53: require("../image/work/dance/hero-4-Who/h4w 決賽-519.jpg"),
        54: require("../image/work/dance/hero-4-Who/h4w 決賽-564.jpg"),
        55: require("../image/work/dance/hero-4-Who/h4w 決賽-700.jpg"),
        56: require("../image/work/dance/hero-4-Who/h4w 決賽-707.jpg"),
        57: require("../image/work/dance/hero-4-Who/h4w 決賽-723.jpg"),
        58: require("../image/work/dance/hero-4-Who/h4w 決賽-725.jpg"),
        59: require("../image/work/dance/hero-4-Who/h4w 決賽-730.jpg"),
        60: require("../image/work/dance/hero-4-Who/h4w 決賽-732.jpg"),
        61: require("../image/work/dance/hero-4-Who/h4w 決賽-751.jpg"),
        62: require("../image/work/dance/hero-4-Who/h4w 決賽-752.jpg"),
        63: require("../image/work/dance/hero-4-Who/h4w 決賽-774.jpg"),
        64: require("../image/work/dance/hero-4-Who/h4w 決賽-808.jpg"),
        65: require("../image/work/dance/hero-4-Who/h4w 決賽-809.jpg"),
        66: require("../image/work/dance/hero-4-Who/h4w 高雄-20.jpg"),
        67: require("../image/work/dance/hero-4-Who/h4w 高雄-267.jpg"),
        68: require("../image/work/dance/hero-4-Who/h4w 高雄-275.jpg"),
        69: require("../image/work/dance/hero-4-Who/h4w 高雄-371.jpg"),
        70: require("../image/work/dance/hero-4-Who/h4w 高雄-381.jpg"),
      },
    },
  },
  life: {
    1: {
      cover: require("../image/work/life/17宜蘭行/17宜蘭-149.jpg"),
      title: "17宜蘭行",
      text: "27",
      images: {
        1: require("../image/work/life/17宜蘭行/17宜蘭-149.jpg"),
        2: require("../image/work/life/17宜蘭行/17宜蘭-165.jpg"),
        3: require("../image/work/life/17宜蘭行/17宜蘭-202.jpg"),
        4: require("../image/work/life/17宜蘭行/17宜蘭-232.jpg"),
        5: require("../image/work/life/17宜蘭行/17宜蘭-243.jpg"),
        6: require("../image/work/life/17宜蘭行/17宜蘭-244.jpg"),
        7: require("../image/work/life/17宜蘭行/17宜蘭-247.jpg"),
        8: require("../image/work/life/17宜蘭行/17宜蘭-251.jpg"),
        9: require("../image/work/life/17宜蘭行/17宜蘭-252.jpg"),
        10: require("../image/work/life/17宜蘭行/17宜蘭-274.jpg"),
        11: require("../image/work/life/17宜蘭行/17宜蘭-307.jpg"),
        12: require("../image/work/life/17宜蘭行/17宜蘭-353.jpg"),
        13: require("../image/work/life/17宜蘭行/17宜蘭-367.jpg"),
        14: require("../image/work/life/17宜蘭行/17宜蘭-375.jpg"),
        15: require("../image/work/life/17宜蘭行/17宜蘭-389.jpg"),
        16: require("../image/work/life/17宜蘭行/17宜蘭-399.jpg"),
        17: require("../image/work/life/17宜蘭行/17宜蘭-402.jpg"),
        18: require("../image/work/life/17宜蘭行/17宜蘭-405.jpg"),
        19: require("../image/work/life/17宜蘭行/17宜蘭-41.jpg"),
        20: require("../image/work/life/17宜蘭行/17宜蘭-418.jpg"),
        21: require("../image/work/life/17宜蘭行/17宜蘭-449.jpg"),
        22: require("../image/work/life/17宜蘭行/17宜蘭-45.jpg"),
        23: require("../image/work/life/17宜蘭行/17宜蘭-478.jpg"),
        24: require("../image/work/life/17宜蘭行/17宜蘭-480.jpg"),
        25: require("../image/work/life/17宜蘭行/17宜蘭-49.jpg"),
        26: require("../image/work/life/17宜蘭行/17宜蘭-82.jpg"),
        27: require("../image/work/life/17宜蘭行/17宜蘭-83.jpg"),
      },
    },
    2: {
      cover: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-1.jpg"),
      title: "22.05.25 霧峰隨手拍",
      text: "15",
      images: {
        1: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-1.jpg"),
        2: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-10.jpg"),
        3: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-11.jpg"),
        4: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-12.jpg"),
        5: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-13.jpg"),
        6: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-14.jpg"),
        7: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-15.jpg"),
        8: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-2.jpg"),
        9: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-3.jpg"),
        10: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-4.jpg"),
        11: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-5.jpg"),
        12: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-6.jpg"),
        13: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-7.jpg"),
        14: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-8.jpg"),
        15: require("../image/work/life/22.05.25 霧峰隨手拍/霧峰隨手拍-9.jpg"),
      },
    },
    3: {
      cover: require("../image/work/life/宮原眼科/h4w-115.jpg"),
      title: "宮原眼科",
      text: "3",
      images: {
        1: require("../image/work/life/宮原眼科/h4w-115.jpg"),
        2: require("../image/work/life/宮原眼科/眼科-1.jpg"),
        3: require("../image/work/life/宮原眼科/眼科-2 P出.png"),
      },
    },
  },
  house: {
    1: {
      cover: require("../image/work/house/house1/DSC_2866.jpg"),
      title: "房屋拍攝",
      text: "15",
      images: {
        1: require("../image/work/house/house1/DSC_2866.jpg"),
        2: require("../image/work/house/house1/IMG_0022.jpg"),
        3: require("../image/work/house/house1/IMG_0056.jpg"),
        4: require("../image/work/house/house1/IMG_0122.jpg"),
        5: require("../image/work/house/house1/IMG_9102.jpg"),
        6: require("../image/work/house/house1/IMG_9108.jpg"),
        7: require("../image/work/house/house1/IMG_9950.jpg"),
        8: require("../image/work/house/house1/_DSC2470.jpg"),
        9: require("../image/work/house/house1/_DSC4186-調整.jpg"),
        10: require("../image/work/house/house1/_DSC4203-調整.jpg"),
        11: require("../image/work/house/house1/_DSC4224-調整.jpg"),
        12: require("../image/work/house/house1/_DSC4233-調整.jpg"),
        13: require("../image/work/house/house1/_LIG3941.jpg"),
        14: require("../image/work/house/house1/_LIG3947.jpg"),
        15: require("../image/work/house/house1/_LIG3953.jpg"),
      },
    },
  },
  art_activity: {
    1: {
      cover: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-1021.jpg"),
      title: "小琉球＿迎王燒王船",
      text: "text",
      images: {
        1: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-1021.jpg"),
        2: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-1051.jpg"),
        3: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-109.jpg"),
        4: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-119.jpg"),
        5: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-12.jpg"),
        6: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-122.jpg"),
        7: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-126.jpg"),
        8: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-139.jpg"),
        9: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-158.jpg"),
        10: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-162.jpg"),
        11: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-167.jpg"),
        12: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-17.jpg"),
        13: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-185.jpg"),
        14: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-19.jpg"),
        15: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-210.jpg"),
        16: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-211.jpg"),
        17: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-217.jpg"),
        18: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-218.jpg"),
        19: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-235.jpg"),
        20: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-258.jpg"),
        21: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-26.jpg"),
        22: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-268.jpg"),
        23: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-27.jpg"),
        24: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-286.jpg"),
        25: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-31.jpg"),
        26: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-33.jpg"),
        27: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-415.jpg"),
        28: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-428.jpg"),
        29: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-443.jpg"),
        30: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-445.jpg"),
        31: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-464.jpg"),
        32: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-490.jpg"),
        33: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-526.jpg"),
        34: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-569.jpg"),
        35: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-591.jpg"),
        36: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-593.jpg"),
        37: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-651.jpg"),
        38: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-654.jpg"),
        39: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-664.jpg"),
        40: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-685.jpg"),
        41: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-69.jpg"),
        42: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-698.jpg"),
        43: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-7.jpg"),
        44: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-73.jpg"),
        45: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-743.jpg"),
        46: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-770.jpg"),
        47: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-778.jpg"),
        48: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-782.jpg"),
        49: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-783.jpg"),
        50: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-79.jpg"),
        51: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-793.jpg"),
        52: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-818.jpg"),
        53: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-859.jpg"),
        54: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-863.jpg"),
        55: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-873.jpg"),
        56: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-9.jpg"),
        57: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-911.jpg"),
        58: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-967.jpg"),
        59: require("../image/work/art_activity/小琉球_迎王燒王船/迎王-973.jpg"),
      },
    },
    2: {
      cover: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-107.jpg"),
      title: "屯區_兒藝節",
      text: "text",
      images: {
        1: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-107.jpg"),
        2: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-119.jpg"),
        3: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-122.jpg"),
        4: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-128.jpg"),
        5: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-147.jpg"),
        6: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-191.jpg"),
        7: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-195.jpg"),
        8: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-203.jpg"),
        9: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-234.jpg"),
        10: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-255.jpg"),
        11: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-263.jpg"),
        12: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-285.jpg"),
        13: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-292.jpg"),
        14: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-300.jpg"),
        15: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-311.jpg"),
        16: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-322.jpg"),
        17: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-331.jpg"),
        18: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-334.jpg"),
        19: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-335.jpg"),
        20: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-344.jpg"),
        21: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-351.jpg"),
        22: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-368.jpg"),
        23: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-389.jpg"),
        24: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-39.jpg"),
        25: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-392.jpg"),
        26: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-398.jpg"),
        27: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-428.jpg"),
        28: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-432.jpg"),
        29: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-435.jpg"),
        30: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-437.jpg"),
        31: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-455.jpg"),
        32: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-477.jpg"),
        33: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-487.jpg"),
        34: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-489.jpg"),
        35: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-513.jpg"),
        36: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-516.jpg"),
        37: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-564.jpg"),
        38: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-587.jpg"),
        39: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-64.jpg"),
        40: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-66.jpg"),
        41: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-78.jpg"),
        42: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-81.jpg"),
        43: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-83.jpg"),
        44: require("../image/work/art_activity/屯區_兒藝節/08.19 屯區-92.jpg"),
      },
    },
    3: {
      cover: require("../image/work/art_activity/后里台灣燈會/DSC03825.jpg"),
      title: "后里台灣燈會",
      text: "text",
      images: {
        1: require("../image/work/art_activity/后里台灣燈會/DSC03825.jpg"),
        2: require("../image/work/art_activity/后里台灣燈會/DSC03975.jpg"),
        3: require("../image/work/art_activity/后里台灣燈會/DSC04325.jpg"),
        4: require("../image/work/art_activity/后里台灣燈會/DSC04518.jpg"),
        5: require("../image/work/art_activity/后里台灣燈會/DSC04570.jpg"),
        6: require("../image/work/art_activity/后里台灣燈會/DSC04863.jpg"),
        7: require("../image/work/art_activity/后里台灣燈會/DSC05290.jpg"),
        8: require("../image/work/art_activity/后里台灣燈會/DSC05306.jpg"),
        9: require("../image/work/art_activity/后里台灣燈會/DSC05315.jpg"),
        10: require("../image/work/art_activity/后里台灣燈會/DSC07881.jpg"),
        11: require("../image/work/art_activity/后里台灣燈會/DSC08216.jpg"),
        12: require("../image/work/art_activity/后里台灣燈會/DSC08371.jpg"),
        13: require("../image/work/art_activity/后里台灣燈會/DSC09066.jpg"),
      },
    },
    4: {
      cover: require("../image/work/art_activity/兒藝節 梧棲區公所 拍攝/DSC03277.jpg"),
      title: "兒藝節 梧棲區公所 拍攝",
      text: "text",
      images: {
        1: require("../image/work/art_activity/兒藝節 梧棲區公所 拍攝/DSC03277.jpg"),
        2: require("../image/work/art_activity/兒藝節 梧棲區公所 拍攝/DSC03462.jpg"),
        3: require("../image/work/art_activity/兒藝節 梧棲區公所 拍攝/DSC03689.jpg"),
        4: require("../image/work/art_activity/兒藝節 梧棲區公所 拍攝/DSC03827.jpg"),
        5: require("../image/work/art_activity/兒藝節 梧棲區公所 拍攝/DSC03907.jpg"),
        6: require("../image/work/art_activity/兒藝節 梧棲區公所 拍攝/DSC04002.jpg"),
      },
    },
    5: {
      cover: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-102.jpg"),
      title: "兒藝節_台中木偶團",
      text: "text",
      images: {
        1: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-102.jpg"),
        2: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-106.jpg"),
        3: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-109.jpg"),
        4: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-11.jpg"),
        5: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-110.jpg"),
        6: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-13.jpg"),
        7: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-149.jpg"),
        8: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-164.jpg"),
        9: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-176.jpg"),
        10: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-181.jpg"),
        11: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-193.jpg"),
        12: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-211.jpg"),
        13: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-216.jpg"),
        14: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-259.jpg"),
        15: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-264.jpg"),
        16: require("../image/work/art_activity/兒藝節_台中木偶團/22.05.28 兒藝節_台中木偶團-83.jpg"),
      },
    },
    6: {
      cover: require("../image/work/art_activity/兒藝節_金宇園掌中劇團/兒藝節_金宇園掌中劇團-105.jpg"),
      title: "兒藝節_金宇園掌中劇團",
      text: "text",
      images: {
        1: require("../image/work/art_activity/兒藝節_金宇園掌中劇團/兒藝節_金宇園掌中劇團-105.jpg"),
        2: require("../image/work/art_activity/兒藝節_金宇園掌中劇團/兒藝節_金宇園掌中劇團-124.jpg"),
        3: require("../image/work/art_activity/兒藝節_金宇園掌中劇團/兒藝節_金宇園掌中劇團-148.jpg"),
        4: require("../image/work/art_activity/兒藝節_金宇園掌中劇團/兒藝節_金宇園掌中劇團-70.jpg"),
        5: require("../image/work/art_activity/兒藝節_金宇園掌中劇團/兒藝節_金宇園掌中劇團-74.jpg"),
        6: require("../image/work/art_activity/兒藝節_金宇園掌中劇團/兒藝節_金宇園掌中劇團-78.jpg"),
        7: require("../image/work/art_activity/兒藝節_金宇園掌中劇團/兒藝節_金宇園掌中劇團-79.jpg"),
        8: require("../image/work/art_activity/兒藝節_金宇園掌中劇團/兒藝節_金宇園掌中劇團-88.jpg"),
        9: require("../image/work/art_activity/兒藝節_金宇園掌中劇團/兒藝節_金宇園掌中劇團-96.jpg"),
      },
    },
    7: {
      cover: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC01777.jpg"),
      title: "媽祖 萬春宮 拍攝",
      text: "text",
      images: {
        1: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC01777.jpg"),
        2: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC01801.jpg"),
        3: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC01807.jpg"),
        4: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC01976.jpg"),
        5: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC01996.jpg"),
        6: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC02213.jpg"),
        7: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC02253.jpg"),
        8: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC02298.jpg"),
        9: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC02330.jpg"),
        10: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC02379.jpg"),
        11: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC02734.jpg"),
        12: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC02736.jpg"),
        13: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC02747.jpg"),
        14: require("../image/work/art_activity/媽祖 萬春宮 拍攝/DSC02815.jpg"),
      },
    },
    8: {
      cover: require("../image/work/art_activity/豐原兒藝節_頑石劇團/DSC04199.jpg"),
      title: "豐原兒藝節_頑石劇團",
      text: "text",
      images: {
        1: require("../image/work/art_activity/豐原兒藝節_頑石劇團/DSC04199.jpg"),
        2: require("../image/work/art_activity/豐原兒藝節_頑石劇團/DSC04235.jpg"),
        3: require("../image/work/art_activity/豐原兒藝節_頑石劇團/DSC04260.jpg"),
        4: require("../image/work/art_activity/豐原兒藝節_頑石劇團/DSC04269.jpg"),
        5: require("../image/work/art_activity/豐原兒藝節_頑石劇團/DSC04271.jpg"),
        6: require("../image/work/art_activity/豐原兒藝節_頑石劇團/DSC04368.jpg"),
        7: require("../image/work/art_activity/豐原兒藝節_頑石劇團/DSC04415.jpg"),
        8: require("../image/work/art_activity/豐原兒藝節_頑石劇團/DSC04505.jpg"),
        9: require("../image/work/art_activity/豐原兒藝節_頑石劇團/DSC04506.jpg"),
        10: require("../image/work/art_activity/豐原兒藝節_頑石劇團/DSC04514.jpg"),
        11: require("../image/work/art_activity/豐原兒藝節_頑石劇團/DSC04533.jpg"),
        12: require("../image/work/art_activity/豐原兒藝節_頑石劇團/DSC04554.jpg"),
        13: require("../image/work/art_activity/豐原兒藝節_頑石劇團/DSC04573.jpg"),
      },
    },
    9: {
      cover: require("../image/work/art_activity/藺草工藝展/藺草工藝展-103.jpg"),
      title: "藺草工藝展",
      text: "text",
      images: {
        1: require("../image/work/art_activity/藺草工藝展/藺草工藝展-103.jpg"),
        2: require("../image/work/art_activity/藺草工藝展/藺草工藝展-107.jpg"),
        3: require("../image/work/art_activity/藺草工藝展/藺草工藝展-108.jpg"),
        4: require("../image/work/art_activity/藺草工藝展/藺草工藝展-111.jpg"),
        5: require("../image/work/art_activity/藺草工藝展/藺草工藝展-115.jpg"),
        6: require("../image/work/art_activity/藺草工藝展/藺草工藝展-117.jpg"),
        7: require("../image/work/art_activity/藺草工藝展/藺草工藝展-126.jpg"),
        8: require("../image/work/art_activity/藺草工藝展/藺草工藝展-210.jpg"),
        9: require("../image/work/art_activity/藺草工藝展/藺草工藝展-219.jpg"),
        10: require("../image/work/art_activity/藺草工藝展/藺草工藝展-224.jpg"),
        11: require("../image/work/art_activity/藺草工藝展/藺草工藝展-228.jpg"),
      },
    },
  },
  people: {
    1: {
      cover: require("../image/work/people/六福村-DBD/六福村-12.jpg"),
      title: "六福村-DBD",
      text: "text",
      images: {
        1: require("../image/work/people/六福村-DBD/六福村-12.jpg"),
        2: require("../image/work/people/六福村-DBD/六福村-13.jpg"),
        3: require("../image/work/people/六福村-DBD/六福村-14.jpg"),
        4: require("../image/work/people/六福村-DBD/六福村-22.jpg"),
        5: require("../image/work/people/六福村-DBD/六福村-23.jpg"),
        6: require("../image/work/people/六福村-DBD/六福村-24.jpg"),
        7: require("../image/work/people/六福村-DBD/六福村-27.jpg"),
      },
    },
    2: {
      cover: require("../image/work/people/史萊姆T/ 史萊姆-小鈴_補拍-11.jpg"),
      title: "史萊姆Ｔ",
      text: "text",
      images: {
        1: require("../image/work/people/史萊姆T/ 史萊姆-小鈴_補拍-11.jpg"),
        2: require("../image/work/people/史萊姆T/ 史萊姆-小鈴_補拍-14.jpg"),
        3: require("../image/work/people/史萊姆T/ 史萊姆-小鈴_補拍-20.jpg"),
        4: require("../image/work/people/史萊姆T/ 史萊姆-小鈴_補拍-32.jpg"),
        5: require("../image/work/people/史萊姆T/ 史萊姆-小鈴_補拍-37.jpg"),
        6: require("../image/work/people/史萊姆T/ 史萊姆-小鈴_補拍-4.jpg"),
        7: require("../image/work/people/史萊姆T/史萊姆-小鈴-24.jpg"),
        8: require("../image/work/people/史萊姆T/史萊姆-小鈴-30.jpg"),
        9: require("../image/work/people/史萊姆T/史萊姆-小鈴-34.jpg"),
        10: require("../image/work/people/史萊姆T/史萊姆-小鈴-37.jpg"),
        11: require("../image/work/people/史萊姆T/史萊姆-小鈴-4.jpg"),
        12: require("../image/work/people/史萊姆T/史萊姆-小鈴-47.jpg"),
      },
    },
    3: {
      cover: require("../image/work/people/白衣女子/11.12 廢墟-1.jpg"),
      title: "白衣女子",
      text: "text",
      images: {
        1: require("../image/work/people/白衣女子/11.12 廢墟-1.jpg"),
        2: require("../image/work/people/白衣女子/11.12 廢墟-11.jpg"),
        3: require("../image/work/people/白衣女子/11.12 廢墟-15.jpg"),
        4: require("../image/work/people/白衣女子/11.12 廢墟-17.jpg"),
        5: require("../image/work/people/白衣女子/11.12 廢墟-20.jpg"),
        6: require("../image/work/people/白衣女子/11.12 廢墟-26.jpg"),
        7: require("../image/work/people/白衣女子/11.12 廢墟-27.jpg"),
        8: require("../image/work/people/白衣女子/11.12 廢墟-28.jpg"),
        9: require("../image/work/people/白衣女子/11.12 廢墟-33.jpg"),
        10: require("../image/work/people/白衣女子/11.12 廢墟-5.jpg"),
      },
    },
    4: {
      cover: require("../image/work/people/廢墟/11.12 廢墟-11.jpg"),
      title: "廢墟",
      text: "text",
      images: {
        1: require("../image/work/people/廢墟/11.12 廢墟-11.jpg"),
        2: require("../image/work/people/廢墟/11.12 廢墟-13.jpg"),
        3: require("../image/work/people/廢墟/11.12 廢墟-18.jpg"),
        4: require("../image/work/people/廢墟/11.12 廢墟-19.jpg"),
        5: require("../image/work/people/廢墟/11.12 廢墟-23.jpg"),
        6: require("../image/work/people/廢墟/11.12 廢墟-30.jpg"),
        7: require("../image/work/people/廢墟/11.12 廢墟-31.jpg"),
        8: require("../image/work/people/廢墟/11.12 廢墟-34.jpg"),
        9: require("../image/work/people/廢墟/11.12 廢墟-41.jpg"),
        10: require("../image/work/people/廢墟/11.12 廢墟-43.jpg"),
        11: require("../image/work/people/廢墟/11.12 廢墟-45.jpg"),
        12: require("../image/work/people/廢墟/11.12 廢墟-5.jpg"),
        13: require("../image/work/people/廢墟/11.12 廢墟-7.jpg"),
        14: require("../image/work/people/廢墟/11.12 廢墟-8.jpg"),
      },
    },
  },
  product: {
    1: {
      cover: require("../image/work/product/產品/B8-2.jpg"),
      title: "產品",
      text: "1",
      images: {
        1: require("../image/work/product/產品/B8-2.jpg"),
        2: require("../image/work/product/產品/B8-4.jpg"),
        3: require("../image/work/product/產品/B8-5.jpg"),
        4: require("../image/work/product/產品/B8-6.jpg"),
        5: require("../image/work/product/產品/B9-1.jpg"),
        6: require("../image/work/product/產品/B9-3.jpg"),
        7: require("../image/work/product/產品/B9-6.jpg"),
        8: require("../image/work/product/產品/B9-7.jpg"),
        9: require("../image/work/product/產品/C24_13.jpg"),
        10: require("../image/work/product/產品/C24_14.jpg"),
        11: require("../image/work/product/產品/C24_5.jpg"),
        12: require("../image/work/product/產品/C24_9.jpg"),
        13: require("../image/work/product/產品/C40-1.jpg"),
        14: require("../image/work/product/產品/C40-6.jpg"),
        15: require("../image/work/product/產品/C40-7.jpg"),
        16: require("../image/work/product/產品/C40-8.jpg"),
        17: require("../image/work/product/產品/C40-9.jpg"),
        18: require("../image/work/product/產品/C42-1.jpg"),
        19: require("../image/work/product/產品/C42-2.jpg"),
        20: require("../image/work/product/產品/C42-3.jpg"),
        21: require("../image/work/product/產品/C42-4.jpg"),
        22: require("../image/work/product/產品/C43_4.jpg"),
        23: require("../image/work/product/產品/C43_5.jpg"),
        24: require("../image/work/product/產品/C43_6.jpg"),
        25: require("../image/work/product/產品/C43_8.jpg"),
        26: require("../image/work/product/產品/F2-10.jpg"),
        27: require("../image/work/product/產品/F2-11.jpg"),
        28: require("../image/work/product/產品/F2-12.jpg"),
        29: require("../image/work/product/產品/F2-13.jpg"),
        30: require("../image/work/product/產品/F2-6.jpg"),
        31: require("../image/work/product/產品/F2-7.jpg"),
        32: require("../image/work/product/產品/F2-8.jpg"),
        33: require("../image/work/product/產品/F2-9.jpg"),
        34: require("../image/work/product/產品/F5-4.jpg"),
        35: require("../image/work/product/產品/OPEN棉-11.jpg"),
        36: require("../image/work/product/產品/OPEN棉-13.jpg"),
        37: require("../image/work/product/產品/OPEN棉-2.jpg"),
        38: require("../image/work/product/產品/OPEN棉-3.jpg"),
        39: require("../image/work/product/產品/OPEN棉-7.jpg"),
        40: require("../image/work/product/產品/S14_11.jpg"),
        41: require("../image/work/product/產品/S14_13.jpg"),
        42: require("../image/work/product/產品/S14_2.jpg"),
        43: require("../image/work/product/產品/S14_3.jpg"),
        44: require("../image/work/product/產品/S14_4.jpg"),
        45: require("../image/work/product/產品/S14_6.jpg"),
        46: require("../image/work/product/產品/S15_1.jpg"),
        47: require("../image/work/product/產品/S15_10.jpg"),
        48: require("../image/work/product/產品/S15_11.jpg"),
        49: require("../image/work/product/產品/S15_2.jpg"),
        50: require("../image/work/product/產品/S15_4.jpg"),
        51: require("../image/work/product/產品/S16-1.jpg"),
        52: require("../image/work/product/產品/S16-2.jpg"),
        53: require("../image/work/product/產品/S16-4.jpg"),
        54: require("../image/work/product/產品/S16-5.jpg"),
        55: require("../image/work/product/產品/S16-8.jpg"),
        56: require("../image/work/product/產品/S3_11.jpg"),
        57: require("../image/work/product/產品/S3_16.jpg"),
        58: require("../image/work/product/產品/S3_3.jpg"),
        59: require("../image/work/product/產品/S3_4.jpg"),
        60: require("../image/work/product/產品/U18_10.png"),
        61: require("../image/work/product/產品/U18_2.jpg"),
        62: require("../image/work/product/產品/U18_9.png"),
        63: require("../image/work/product/產品/U8-1.jpg"),
        64: require("../image/work/product/產品/U8-10.jpg"),
        65: require("../image/work/product/產品/U8-11.jpg"),
        66: require("../image/work/product/產品/U8-12.jpg"),
        67: require("../image/work/product/產品/U8-13.jpg"),
        68: require("../image/work/product/產品/U8-14.jpg"),
        69: require("../image/work/product/產品/U8-2.jpg"),
        70: require("../image/work/product/產品/U8-3.jpg"),
        71: require("../image/work/product/產品/U8-4.jpg"),
        72: require("../image/work/product/產品/U8-5.jpg"),
        73: require("../image/work/product/產品/U8-6.jpg"),
        74: require("../image/work/product/產品/U8-7.jpg"),
        75: require("../image/work/product/產品/U8-8.jpg"),
        76: require("../image/work/product/產品/U8-9.jpg"),
        77: require("../image/work/product/產品/舒緩修復爆水保養組-1.jpg"),
        78: require("../image/work/product/產品/舒緩修復爆水保養組-10.jpg"),
        79: require("../image/work/product/產品/舒緩修復爆水保養組-11.jpg"),
        80: require("../image/work/product/產品/舒緩修復爆水保養組-3.jpg"),
        81: require("../image/work/product/產品/舒緩修復爆水保養組-4.jpg"),
        82: require("../image/work/product/產品/舒緩修復爆水保養組-7.jpg"),
        83: require("../image/work/product/產品/舒緩修復爆水保養組-8.jpg"),
        84: require("../image/work/product/產品/舒緩修復爆水保養組-9.jpg"),
        85: require("../image/work/product/產品/黑瓶洗髮系列_12.jpg"),
        86: require("../image/work/product/產品/黑瓶洗髮系列_16.jpg"),
        87: require("../image/work/product/產品/黑瓶洗髮系列_19.jpg"),
        88: require("../image/work/product/產品/黑瓶洗髮系列_4.jpg"),
        89: require("../image/work/product/產品/黑瓶洗髮系列_7.jpg"),
      },
    },
    2: {
      cover: require("../image/work/product/模型/DSC012801.jpg"),
      title: "模型",
      text: "text",
      images: {
        1: require("../image/work/product/模型/DSC012801.jpg"),
        2: require("../image/work/product/模型/DSC01283-1.jpg"),
        3: require("../image/work/product/模型/DSC01292-1.jpg"),
      },
    },
  },
  toy: {
    1: {
      cover: require("../image/work/product/模型/DSC012801.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    2: {
      cover: require("../image/work/product/模型/DSC012801.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    3: {
      cover: require("../image/work/product/模型/DSC012801.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    4: {
      cover: require("../image/work/product/模型/DSC012801.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
    5: {
      cover: require("../image/work/product/模型/DSC012801.jpg"),
      title: "1",
      text: "text",
      images: {},
    },
  },
};
export default WorkData;
